name: Laravel CI/CD

on:
  push:
    branches:
      - main   # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger the workflow on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Specify your PHP version
          extensions: mbstring, xml, bcmath, mysql
          coverage: xdebug

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: vendor/bin/phpunit --env=testing

      - name: Build and Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Building and deploying your Laravel application..."
          # Add your deployment commands here
          # For example:
          # rsync -avz --exclude='node_modules' --exclude='.git' ./ user@server:/path/to/deploy
